# Generated by Django 4.2.29 on 2026-04-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_align_contacts_with_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associatedcontact',
            options={'ordering': ('name',), 'verbose_name': 'associated contact', 'verbose_name_plural': 'associated contacts'},
        ),
    ]
