# Generated by Django 4.2.29 on 2026-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='last_analyzed_at',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmotionalAnalysis',
        ),
    ]
