# Generated by Django 5.1.8 on 2026-03-28 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='users.therapist'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_ptr',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='patient_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='user_ptr',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='therapist_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
