# Generated by Django 5.1.8 on 2026-03-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_therapist_alter_patient_user_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='therapist',
        ),
        migrations.CreateModel(
            name='TherapistPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_links', to='users.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='users.therapist')),
            ],
            options={
                'verbose_name': 'therapist-patient relationship',
                'verbose_name_plural': 'therapist-patient relationships',
                'constraints': [models.UniqueConstraint(fields=('patient', 'therapist'), name='unique_patient_therapist_relationship')],
            },
        ),
    ]
