# Generated by Django 4.2.29 on 2026-04-17 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_two_factor_pending_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('clinic', 'Clinic')], max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('clinic', 'Clinic')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
            },
        ),
        migrations.RemoveConstraint(
            model_name='therapistpatient',
            name='unique_patient_therapist_relationship',
        ),
        migrations.AddField(
            model_name='therapistpatient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='therapistpatient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('clinic_admin', 'Clinic Admin'), ('therapist', 'Therapist'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='therapistpatient',
            constraint=models.UniqueConstraint(fields=('therapist', 'patient'), name='unique_therapist_patient'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.organisation'),
        ),
    ]
