# Generated by Django 4.2.29 on 2026-04-19 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('individual', 'Individual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('therapist', 'Therapist'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('clinic', 'Clinic')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('periodicity', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('ini_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.organisation')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='OrganisationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='users.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organisation member',
                'verbose_name_plural': 'organisation members',
                'unique_together': {('user', 'organisation')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(related_name='members', through='users.OrganisationMember', to='users.organisation'),
        ),
    ]
