# Generated by Django 4.2.29 on 2026-04-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_organisation_plan_remove_user_organisation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
