# Generated by Django 4.2.29 on 2026-05-15 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_limit_organisationmember_to_one_org_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacioOrganitzacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('dataCreacio', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCaducitat', models.DateTimeField(blank=True, null=True)),
                ('usat', models.BooleanField(default=False)),
                ('idOrganitzacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitacions', to='users.organisation')),
            ],
            options={
                'verbose_name': "invitació d'organització",
                'verbose_name_plural': "invitacions d'organització",
            },
        ),
    ]
