# Generated by Django 4.2.29 on 2026-05-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_invitacioorganitzacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacioorganitzacio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
