# Generated by Django 4.2.29 on 2026-05-22 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0004_supporttherapist_request_status'),
        ('analysis', '0003_simplify_emotionalanalysis'),
        ('users', '0013_user_legal_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('validation_note', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.IntegerField(default=0)),
                ('last_escalation_at', models.DateTimeField(blank=True, null=True)),
                ('notification_status', models.CharField(choices=[('not_notified', 'Not notified'), ('notified', 'Notified'), ('acknowledged', 'Acknowledged')], default='not_notified', max_length=20)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('emotional_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='analysis.emotionalanalysis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='users.patient')),
                ('validating_therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_alerts', to='users.therapist')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('error_message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to='contacts.associatedcontact')),
            ],
            options={
                'verbose_name': 'alert notification',
                'verbose_name_plural': 'alert notifications',
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['alert', '-sent_at'], name='alerts_aler_alert_i_3be539_idx'), models.Index(fields=['status'], name='alerts_aler_status_92b91f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['patient', '-created_at'], name='alerts_aler_patient_6978ea_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alerts_aler_status_e70a14_idx'),
        ),
    ]
