# Generated by Django 4.2.29 on 2026-05-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionalanalysis',
            name='risk_level',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20),
        ),
    ]
