from django.http import JsonResponse
from django.urls import path

from apps.users.views import (
    AccountActivationView,
    ChangePasswordView,
    ConsentDocumentView,
    DeleteAccountView,
    LoginView,
    LogoutView,
    MeView,
    PasswordForgotView,
    PasswordResetView,
    PatientConsentAcceptView,
    PatientConsentRejectView,
    PatientRegistrationView,
    TherapistRegistrationView,
    TherapistPatientDeactivateView,
    TherapistPatientListView,
    TherapistPatientDetailView,
    TwoFactorDisableView,
    TwoFactorEnableView,
    TwoFactorSetupView,
    TwoFactorVerifyView,
    ClinicStatsView,
    OrganisationDetailView,
    InvitacioOrganitzacioCreateView,
    TherapistAdminDetailView,
    ClinicTherapistListView,
    TherapistDashboardView,
)

def index(request):
    return JsonResponse({"message": "Reflexia API working!"})


urlpatterns = [
    path('', index),
    path('consent/document/', ConsentDocumentView.as_view(), name='consent-document'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('delete-account/', DeleteAccountView.as_view(), name='delete-account'),
    path('password/forgot/', PasswordForgotView.as_view(), name='password-forgot'),
    path('password/reset/', PasswordResetView.as_view(), name='password-reset'),
    path('me/', MeView.as_view(), name='me'),
    path('register/therapist/', TherapistRegistrationView.as_view(), name='therapist-register'),
    path('register/patient/', PatientRegistrationView.as_view(), name='patient-register'),
    path('patients/', TherapistPatientListView.as_view(), name='patient-list'),
    path('patients/<uuid:patient_id>/', TherapistPatientDetailView.as_view(), name='patient-detail'),
    path('patients/deactivate/', TherapistPatientDeactivateView.as_view(), name='patient-deactivate'),
    path('activate/account/', AccountActivationView.as_view(), name='account-activate'),
    path('dashboard/therapist/', TherapistDashboardView.as_view(), name='therapist-dashboard'),
    path('consent/accept/', PatientConsentAcceptView.as_view(), name='patient-consent-accept'),
    path('consent/reject/', PatientConsentRejectView.as_view(), name='patient-consent-reject'),
    path('2fa/setup/', TwoFactorSetupView.as_view(), name='two-factor-setup'),
    path('2fa/enable/', TwoFactorEnableView.as_view(), name='two-factor-enable'),
    path('2fa/verify/', TwoFactorVerifyView.as_view(), name='two-factor-verify'),
    path('2fa/disable/', TwoFactorDisableView.as_view(), name='two-factor-disable'),
    path('admin/stats/clinic/', ClinicStatsView.as_view(), name='clinic-stats'),
    path('admin/organisations/<uuid:organisation_id>/', OrganisationDetailView.as_view(), name='organisation-detail'),
    path('admin/organisations/invitations/', InvitacioOrganitzacioCreateView.as_view(), name='organisation-invitation-create'),
    path('admin/therapists/<uuid:user_id>/', TherapistAdminDetailView.as_view(), name='therapist-admin-detail'),
    path('admin/clinic/therapists/', ClinicTherapistListView.as_view(), name='clinic-therapist-list'),
]
