name: CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codi
        uses: actions/checkout@v3

      - name: Instal·lar dependències backend
        working-directory: reflexia-backend
        run: pip install -r requirements.txt

      - name: Executar linting backend
        working-directory: reflexia-backend
        run: python manage.py check

      - name: Executar tests backend
        working-directory: reflexia-backend
        run: python manage.py test

      - name: Instal·lar dependències frontend
        working-directory: reflexia-frontend
        run: npm install

      - name: Executar linting frontend
        working-directory: reflexia-frontend
        run: npm run lint
